language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_f81e0b38d6f8_key -iv $encrypted_f81e0b38d6f8_iv
  -in .ftppass.enc -out .ftppass -d
- npm install -g grunt-cli
# before_script:
# - npm install -g bower
# - bower install
